/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financiera.presentacion.vistas;

import financiera.dominio.Credito;
import financiera.dominio.Cuota;
import financiera.presentacion.adaptador.IServicioPublicoCreditoInformarCreditoFinalizadoErrorServicioFaultFaultMessage;
import financiera.presentacion.interfaces.IAbonarCuota;
import financiera.presentacion.presentadores.PAbonarCuota;
import financiera.presentacion.vistas.render.Render;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author usuario
 */
public class VAbonarCuota extends javax.swing.JDialog implements IAbonarCuota {

    /**
     * Creates new form VAbonarCuota
     */
    PAbonarCuota presentador;
    public VAbonarCuota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.presentador = new PAbonarCuota(this);
        this.cbxModoPago.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    designarModoPago();
                }
            }

        });
        this.txtMonto.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
              actualizarMontoTotal();
            }
        });
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    @Override
    public void designarModoPago() {
               if(this.cbxModoPago.getSelectedItem().equals("Por Monto")){
                   this.tbCuotas.setEnabled(false);
                   this.txtMonto.setEnabled(true);
               }else{
                   this.tbCuotas.setEnabled(true);
                   this.txtMonto.setEnabled(false);
               }
    }
    public boolean esNumerico(String texto)
    {
        try{
            if(texto!=null){
                Double.parseDouble(texto);
                return true;
            }
        }catch(NumberFormatException nfe){
            return false;
        }
        return false;
    }
    public void actualizarMontoTotal(double adicion){
        double monto = Double.parseDouble(this.lbTotal.getText());
        this.lbTotal.setText(String.valueOf(monto+adicion));
    }
    public void actualizarMontoTotal(){
        String monto = this.txtMonto.getText();
        if(esNumerico(monto) && !monto.isEmpty()){
            this.lbTotal.setText(monto);
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un monto correcto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCuotas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbxModoPago = new javax.swing.JComboBox<>();
        btnValidar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abonar Cuota");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DNI:");

        txtDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDni.setText("33000007");

        tbCuotas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbCuotasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbCuotas);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cuotas Impagas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Monto:");

        txtMonto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total:");

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotal.setText("0.0");

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbxModoPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxModoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnValidar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Modo de Pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxModoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxModoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lbTotal))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        String dni = this.txtDni.getText();
        if(esNumerico(dni) && !dni.isEmpty()){
             this.presentador.ingresarCliente(dni);
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un DNI correcto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void tbCuotasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCuotasMousePressed
        if(evt.getClickCount()==1){
            try{
               if(this.tbCuotas.isEnabled()){
                   int linea  = this.tbCuotas.getSelectedRow();
                    boolean isSelected = this.tbCuotas.isColumnSelected(8);
                    if(isSelected){
                        double monto = (double) this.tbCuotas.getValueAt(linea, 6);
                        boolean tilde = (boolean) this.tbCuotas.getValueAt(linea, 8);
                        if(!tilde){
                            actualizarMontoTotal(monto);
                        }else{
                             actualizarMontoTotal(-monto);
                        }
                    }
               }
                
                
            }catch(Exception ex){
                
            }
        }
    }//GEN-LAST:event_tbCuotasMousePressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(!this.lbTotal.getText().startsWith("0")){
            if(this.cbxModoPago.getSelectedItem().equals("Por Monto")){
                    double monto = Double.parseDouble(this.lbTotal.getText());
                    this.presentador.abonarCuota(monto);
          
            }else{
                        for(int i=0;i<this.tbCuotas.getRowCount();i++)
                        {
                            if((boolean)this.tbCuotas.getValueAt(i, 8))
                            {
                                int nroCredito = (int) this.tbCuotas.getValueAt(i, 0);
                                int nroCuota = (int) this.tbCuotas.getValueAt(i, 2);
                                this.presentador.abonarCuota(nroCredito,nroCuota);
                            }
                        }
                        
            }  
            try {
                        this.presentador.finalizarPago();
            } catch (IServicioPublicoCreditoInformarCreditoFinalizadoErrorServicioFaultFaultMessage ex) {
                        Logger.getLogger(VAbonarCuota.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }else{
                    JOptionPane.showMessageDialog(this, "Asegúrese de haber ingresado un monto o de haber seleccionado las cuotas a pagar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JComboBox<String> cbxModoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tbCuotas;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarTablaCuotas(ArrayList<Credito> creditos, boolean seSelecciona) {
        boolean[] editable = {false,false,false,false,false,false,false,false,seSelecciona};
        this.tbCuotas.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel dt = new DefaultTableModel(new String[]{"NRO CREDITO", "ESTADO","NRO CUOTA","FECHA VENCIMIENTO", "MONTO INICIAL","INTERES","MONTO NETO", "SALDO PENDIENTE","SELECCIONAR"}, 0) {
 
            Class[] types = new Class[]{
                java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,java.lang.Boolean.class
            };
 
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            @Override
            public boolean isCellEditable(int row, int column){
                return editable[column];
            }
        };
        if(creditos.size() > 0){
            creditos.forEach((c) -> {
                for(int i=0; i< c.getCuotas().size(); i++){
                    if(c.getCuotas().get(i).getMontoAdeudado()!=0){
                        Object fila[] = new Object[9];
                        fila[0] = c.getNroCredito();
                        fila[1] = c.getEstado().name();
                        fila[2] = c.getCuotas().get(i).getNroCuota();
                        fila[3] = new SimpleDateFormat("dd/MM/yyyy").format(c.getCuotas().get(i).getFechaVencimiento());
                        fila[4] = Math.round(c.getCuotas().get(i).getMontoTotal()*100d)/100d;
                        fila[5] = Math.round(c.getCuotas().get(i).getInteres()*100d)/100d;
                        fila[6] = Math.round(c.getCuotas().get(i).getMontoNeto()*100d)/100d;
                        fila[7] = Math.round(c.getCuotas().get(i).getMontoAdeudado()*100d)/100d;
                        fila[8] = false;
                        dt.addRow(fila);
                    }
                }
            });
        }
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(dt);
         this.tbCuotas.setRowSorter(sorter);
        
        this.tbCuotas.setModel(dt);
        this.tbCuotas.getRowSorter().toggleSortOrder(3);
    }

    @Override
    public void bloquearAccesoTablaYMonto() {
       this.txtMonto.setEnabled(false);
       this.btnAceptar.setEnabled(false);
       this.cbxModoPago.setEnabled(false);
    }

    @Override
    public void cargarComboBox() {
        this.cbxModoPago.removeAllItems();
        this.cbxModoPago.addItem("Por Monto");
        this.cbxModoPago.addItem("Por Cuotas Seleccionadas");
    }
    @Override
     public void permitirAccesoTablaYMonto() {
        this.txtMonto.setEnabled(true);
        this.txtDni.setEnabled(false);
        this.btnValidar.setEnabled(false);
        this.btnAceptar.setEnabled(true);
        this.cbxModoPago.setEnabled(true);
    }

    @Override
    public void informarClienteInexistente() {
        JOptionPane.showMessageDialog(this, "No se encontró un cliente con el DNI ingresado.", "Error", JOptionPane.ERROR_MESSAGE);
    }

  
}
